### PR TITLE
Add Gzip text compression configuration to installation instructions

### PR DESCRIPTION
**Pull request by translucentfocus**
I used [Lighthouse](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/speed/get-started) in Chromium-based Edge to analyze the performance of Mainsail. It detected that Gzip text compression was not being used.  I opened `/etc/nginx/nginx.conf` and discovered that by default, Gzip is enabled, but only the text of Mainsail's files are compressed because the config lines for Gzip compression are commented out.

I've tested on a Raspberry Pi 3B+ and had no issues (but Mainsail loads noticeably faster 💨).  I'll reach out on Discord and see if anyone with a Pi Zero wants to test and see if they have issues due to increased CPU usage.

**Before Gzip configuration**
image

***After Gzip configuration***
image

@meteyou It won't hurt my feelings if you reject this pull request 😊

### CODE REVIEW

**Comment by meteyou** [comment]
of course, i will test it on the pi zero. would it be possible to configure this directly in the mainsail.conf?

**Comment by translucentfocus** [comment]
> 
> 
> of course, i will test it on the pi zero. would it be possible to configure this directly in the mainsail.conf?

Great question! I'm not famliar with it enough yet, but I've asked on Discord.  Btw... it looks like initial test results show having it on for the Pi Zero is too much.  Modifying my PR to indicate that

**Comment by translucentfocus** [comment]
> 
> 
> of course, i will test it on the pi zero. would it be possible to configure this directly in the mainsail.conf?

Hmmm... I haven't been able to find `mainsail.conf` anywhere... did you mean `moonraker.conf`?

**Comment by meteyou** [comment]
sry. i mean this file `/etc/nginx/sites-available/mainsail`

**Comment by translucentfocus** [comment]
> 
> 
> sry. i mean this file `/etc/nginx/sites-available/mainsail`

Ah!  Yes, this would make sense as it would only apply to mainsail then vs globally.  Will update my PR in the next couple of days.

**Pull request closed without merging**
