### PR TITLE
Add Language Change

### PR DESCRIPTION
**Pull request by winbin**

### CODE REVIEW

**Comment by meteyou** [comment]
thank you for the PR. i currently have only one problem... I have no idea how to check these language files.
but i will come up with something in the next few days. the next question is who will update the chinese files regularly afterwards?

**Comment by winbin** [comment]
> thank you for the PR. i currently have only one problem... I have no idea how to check these language files.
> but i will come up with something in the next few days. the next question is who will update the chinese files regularly afterwards?

i will update chinese files regularly

**Comment by meteyou** [comment]
ok thx! i will check the implementation in the next days and then i can merge it!

**Comment by meteyou** [comment]
i have now taken a close look at your work. it looks very promising. could you just restructure the structure of the language file a little? 

For example, rename `Dashboard.Home` to `ControlPanel.Home`.
and in SettingsPanels: `Setting.RenameFile` to `Settings.ConfigFilesPanel.RenameFile`

and pls update the ExtruderPanel, ToolsPanel and WebcamPanel.

**Comment by winbin** [comment]
ok, i will to edit it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
