### PR TITLE
Some Improvments

### PR DESCRIPTION
**Pull request by eliteSchwein**
Hey!

i just added

- virtual Keyboard
- neopixel support
- scale support
- main background
- fix some buggs

### CODE REVIEW

**Comment by eliteSchwein** [comment]
eh i disabled the overlayDisconnect dialog and forgot to re-enable it opsi

**Comment by meteyou** [comment]
I saw your fork and I like many many many things of it. I have to build one and test all this functions. Where do you get the resource stats?

**Comment by eliteSchwein** [comment]
Which Ressource stats? Ressource monitor? I removed it temporarly because i put it on a seperate project for deeper development (hsinfopanel repo)

**Comment by eliteSchwein** [comment]
i will merge later your update into my pull request and my mainsail repo

**Comment by eliteSchwein** [comment]
everthing is tested and working fine, you can safely merge now :)

**Comment by meteyou** [comment]
Thx. I will check this in the next days. Thank you very much...

**Comment by eliteSchwein** [comment]
no Problem, i will make a seperate pull request as soon as the ressource monitor is ready, also for the Scale module you need this: https://github.com/eliteSchwein/hx711server

**Comment by eliteSchwein** [comment]
I found a few buggs, as example the dashboard console component doesnt work with the virtual keyboard yet, and preheat doesnt save anymore...

**Comment by eliteSchwein** [comment]
But i work currently on a other project called mooncord, so i fix it after i am done with that project

**Comment by eliteSchwein** [comment]
i removed my custom preheat panel and added virtual keyboard support everywhere

**Comment by meteyou** [comment]
I will finish the current release and then we will finish this pr. Is that ok for you?

**Comment by eliteSchwein** [comment]
Yeah and i keep updating my fork

**Comment by eliteSchwein** [comment]
-added lightmode

i will soon seperate push request for each feature (when someone explains me how lol)

**Comment by johanmalay** [comment]
The virtual keyboard is exciting. That'll be a huge boon to usability on touchscreens.

**Comment by eliteSchwein** [comment]
i host now a remote version of my mods: https://mainsail.eliteschw31n.de/

**Comment by johanmalay** [comment]
@eliteSchwein that's neat. I'm trying it out now. How does the virtual keyboard work? I enabled it under the settings, but when I tap into a field, all I get is a little modal at the bottom of the screen with the field name and value, no keyboard.
screenshot

**Comment by eliteSchwein** [comment]
You enable it in the interface settings

**Comment by johanmalay** [comment]
Yeah, I have it enabled there.

**Comment by johanmalay** [comment]
Ahh, ok, I figured it out. It works on the console. I'm trying to use it on the temperatures on the dashboard. Looks like you just need to add the triggers for it on those fields.

**Comment by johanmalay** [comment]
Would also be great if it worked in the file editors.

**Comment by eliteSchwein** [comment]
I forgot it in the temps? Opsi

File editor is know that it isnt currently working, i will add it soon there!

**Comment by johanmalay** [comment]
Sweet! Thanks for this. This makes a very compelling argument for mainsail over the competition. I have a 7" screen on my pi attached to my printer running in kiosk mode, so having a touch keyboard built in is amazing.

**Comment by johanmalay** [comment]
A side note regarding initial setup when trying to add a printer for the first time. It'd be cool to have a toggle button to enable the virtual keyboard on that modal. That way it'd be easier to use the remote version on a touch only device like this.

Mockup attached to explain what I mean.
Add printer kb example

**Comment by eliteSchwein** [comment]
You use a 7" on the pi? I have also a 7" on the pi :)

**Comment by johanmalay** [comment]
Great thanks!

**Comment by johanmalay** [comment]
Also, the neopixel controller is sweet, love it.

**Comment by eliteSchwein** [comment]
dumb question does it work? didnt tested it yet, i must wait for a component for my board....

**Comment by johanmalay** [comment]
Yes it works great! I just popped in the alias for my neopixel config, went to the dashboard and the control screen appeared.

The only thing I think you could add to it would be an on/off toggle for the neopixels. Also, down the road, adding support for multiple configs with some way to control them independently would be good, but I only have one config for now so this is great.

**Comment by eliteSchwein** [comment]
ok, i will add a turn off button :)

for the multiple config part, i will try to  make it automatic

**Comment by johanmalay** [comment]
Yeah, I wouldn't be able to test that either, I think this as you have it, is a great starting point. Something that could be released and be useful for people.

**Comment by eliteSchwein** [comment]
when i think about it, i can just add some dummy strips to my printer config to test it

**Comment by johanmalay** [comment]
Yeah, seems it'd be easy enough to add multiple configs under the settings section, it's more about how to make the ui elegant on the dashboard. Don't want to clutter it up with multiple color pickers necessarily.

**Comment by johanmalay** [comment]
Guess you could have little buttons in the widget to select which config you're editing.

**Comment by eliteSchwein** [comment]
virtual keyboard on setup should now work

**Comment by johanmalay** [comment]
Nice! Can you add a "Cancel" button to the "Add Printer" dialog so it takes you back to the "Select Printer" dialog?

**Comment by eliteSchwein** [comment]
i will close this PR now, i will make seperate PRs for each added feature

**Pull request closed without merging**
